import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './contexts/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        secondary: '#b9c7e0',
        'on-surface': '#e5e2e1',
        'on-tertiary-fixed': '#ffffff',
        'tertiary-container': '#8691a7',
        'on-primary-fixed': '#ffffff',
        'on-secondary-fixed': '#0d1c2f',
        'on-tertiary': '#111c2d',
        'surface-container-low': '#1c1b1b',
        surface: '#131313',
        'surface-bright': '#3a3939',
        error: '#ffb4ab',
        'error-container': '#93000a',
        background: '#131313',
        'on-surface-variant': '#c6c6c6',
        'primary-fixed': '#5d5f5f',
        'surface-variant': '#353534',
        'on-primary-fixed-variant': '#e2e2e2',
        'outline-variant': '#474747',
        'on-primary': '#1a1c1c',
        'on-error-container': '#ffdad6',
        'primary-container': '#d4d4d4',
        'inverse-surface': '#e5e2e1',
        'tertiary-fixed': '#545f73',
        'surface-container': '#201f1f',
        'inverse-on-surface': '#313030',
        'secondary-fixed': '#b9c7e0',
        'surface-container-high': '#2a2a2a',
        'on-primary-container': '#000000',
        outline: '#919191',
        'surface-tint': '#c6c6c7',
        'on-background': '#e5e2e1',
        primary: '#ffffff',
        'on-tertiary-container': '#000000',
        'surface-container-lowest': '#0e0e0e',
        tertiary: '#d8e3fb',
        'primary-fixed-dim': '#454747',
        'secondary-container': '#3a485c',
        'on-secondary': '#0d1c2f',
        'tertiary-fixed-dim': '#3c475a',
        'surface-dim': '#131313',
        'on-secondary-fixed-variant': '#2e3c50',
        'on-tertiary-fixed-variant': '#d8e3fb',
        'inverse-primary': '#5d5f5f',
        'secondary-fixed-dim': '#9eacc4',
        'on-error': '#690005',
        'surface-container-highest': '#353534',
        'on-secondary-container': '#d5e3fd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [forms],
};

export default config;
